SIMANDRECDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SIMANDRECDIR ; python config.py ;
alias Sim3770="python ${SIMANDRECDIR}/init3770.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimNewJpsi="python ${SIMANDRECDIR}/initNewJpsi.py"
