setenv SIMANDRECDIR "${BaskDIR}/SimAndRec"
alias SimJpsi "python ${SIMANDRECDIR}/initJpsi.py"
alias SimNewJpsi "python ${SIMANDRECDIR}/initNewJpsi.py"
alias SimPsi2S "python ${SIMANDRECDIR}/initPsi2S.py"
alias Sim4180 "python ${SIMANDRECDIR}/init4180.py"
