from SimWithKKMC import SimWithKKMC 
class Sim4600(SimWithKKMC) : 
    def __init__(self):
        SimWithKKMC.__init__(self)
        self.SetOpt('KKMC', 'CMSEnergy',' 4.6')
        self.SetOpt('KKMC', 'BeamEnergySpread','0.0011')
        self.SetOpt('KKMC', 'NumberOfEventPrinted','10')
        self.SetOpt('KKMC', 'GeneratePsi4260','true')
        self.SetOpt('KKMC', 'ResParameterPs7',' {4.6e0, 95e-3, 0.47e-6}')
        self.SetOpt('KKMC', 'ModeIndexExpXS','-2')
        self.SetOpt('KKMC', 'ParticleDecayThroughEvtGen',' true')
        self.SetOpt('KKMC', 'ThresholdCut','  4.573')
        self.SetOpt('KKMC', 'RadiationCorrection',' 1')
        self.SetOpt('KKMC', 'TagISR',' 1')
        self.SetOpt('KKMC', 'TagFSR',' 1')
        self.SetOpt('EvtDecay', 'userDecayTableName',' "ll.dec"')
        self.SetOpt('EvtDecay', 'PdtTableDir',' "mypdt.table"')
        self.SetOpt('EvtDecay', 'statDecays',' true')
        self.SetOpt('RealizationSvc', 'RunIdList',' {-35227}')
        self.SetOpt('BesRndmGenSvc', 'RndmSeed',' 1001')
        self.SetOpt('RootCnvSvc', 'digiRootOutputFile','"/scratchfs2/bes/kangxianwei/maxx/analysis/4600/mc/pomega/rtraw/sim_inclu_1001.rtraw"')
        self.SetOpt('MessageSvc', 'OutputLevel',' 5')
        self.SetOpt('ApplicationMgr', 'EvtMax',' 10000')
